#! /bin/ksh
version2="Version: 2.9.6.RELEASE"
template7="Template: base-tomcat-7"
version3="Version: 3.0.2.RELEASE"
template8="Template: base-tomcat-8"
catalinehome_v296="/opt/tcserver/releases/vfabric-tc-server-standard-2.9.6.RELEASE"
catalinehome_v302="/opt/tcserver/v3.0.2/tomcat-8.0.15.A.RELEASE"

encryptpassword ( ) {
   print $1
   keyandkeystoreencrypted=false
   if grep -q  PropertyDecoder.decoder_prefix $2/conf/catalina.properties
   then
       print "Found PropertyDecoder.decoder_prefix"
       decorder_prefix=true
   else
       print "PropertyDecoder.decoder_prefix not found"
       decorder_prefix=false
   fi
   print "one"
   if   [[ $(grep -c ".*key.*\.password\s*=\s*tcEnc" $2/conf/catalina.properties) -gt 1 ]]
   then
       print "Both key and keystore passwords are alreay encrypted"
       both_encrypted=true
   else
       if [[ $(grep -c ".*key.*\.password\s*=\s*xxxxv3r" $2/conf/catalina.properties) -gt 1 ]]
       then
           keyandkeystoreencrypted=true
           print "inside key and keystore"
       fi
       if grep -q ".*key\.password\s*=\s*xxxxv3r" $2/conf/catalina.properties
       then
           if   !  grep -q ".*PropertyDecoder\.passphrase\s*=\s*passkey" $2/conf/catalina.properties > /dev/null
           then
               print "Line containing passkey is not found"
               if [ $decorder_prefix == true ]
               then
                   sed -i '/base.shutdown.port=/r addsecondline.txt' $2/conf/catalina.properties
                    print "Adding two lines when decorder_prefix == true 1"
               else
                   sed -i '/base.shutdown.port=/r addthreelines.txt' $2/conf/catalina.properties
                    print "Adding three lines when decorder_prefix == false 2"
               fi
           elif [ $decorder_prefix == false ]
           then
               sed -i '/PropertyDecoder.passphrase/r addoneline.txt' $2/conf/catalina.properties
                    print "Adding one line when decorder_prefix == false 3"
           fi
           if  [[ $1 == "v296" ]]
           then
               sed -i -e 's/d1sc0v3r/tcEnc:v29612345678=/g' $2/conf/catalina.properties
               keyencrypted=true
               print "keypassword just got changed"
           elif [[ $1 == "v302" ]]
           then
               sed -i -e 's/d1sc0v3r/tcEnc:v30212345678=/g' $2/conf/catalina.properties
               keyencrypted=true
               print "keypassword just got changed"
           fi
       fi
       if grep -q ".*keystore\.password\s*=\s*xxxxv3r" $2/conf/catalina.properties
       then
           if   ! grep -q ".*PropertyDecoder\.passphrase\s*=\s*passkey" $2/conf/catalina.properties > /dev/null
           then
               if [ $decorder_prefix == true ]
               then
                   sed -i '/base.shutdown.port=/r addsecondline.txt' $2/conf/catalina.properties
               else
                   sed -i '/base.shutdown.port=/r addthreelines.txt' $2/conf/catalina.properties
               fi
           elif [ $decorder_prefix == false ]
           then
               sed -i 'PropertyDecoder.passphrase/r addoneline.txt' $2/conf/catalina.properties
           fi
           if  [[ $1 == "v296" ]]
           then
               print "1"
               sed -i -e 's/d1sc0v3r/tcEnc:v29612345678=/g' $2/conf/catalina.properties
               keystoreencrypted=true
               print "keystorepassword v296 just got changed"
           elif [[ $1 == "v302" ]]
           then
               print "2"
               sed -i -e 's/d1sc0v3r/tcEnc:v30212345678=/g' $2/conf/catalina.properties
               keystoreencrypted=true
               print "keystorepassword  302 just got changed"
           fi
       fi
       if [ $keyandkeystoreencrypted == true ]
       then
           print "Both key and keystore passwords have been encrypted"
       elif  [ $keyencrypted == true ]
       then
           print "Only Key password has been encrypted"
       elif [ $keystoreencrypted == true ]
       then
           print "Only Keystore password has ben encrypted"
       fi
       if  [[  $keyandkeystoreencrypted == true  ||  $keyencrypted == true  ||  $keystoreencrypted == true  ]]
       then
           print " JVM marked for restart "
       else
           print " Password to be encrypted is not found"
       fi
   fi
}
#cd /opt/tcserver/servers
cd /home/tomcat
#for i in $( ls -d /opt/tcserver/servers/* |grep -v lost+found);
for i in $( ls -d /home/tomcat/* |grep -v lost+found);
do
   if [[ -d $i ]];then
       print $i
       if [[ -f $i/README.txt ]]
       then
           if grep -q  "$version2" $i/README.txt && grep -q "$template7" $i/README.txt
           then
               echo "Found Tomcat 2.9.6 version with Tomcat7"
               encryptpassword  v296 $i
           elif grep -q  "$version3" $i/README.txt && grep -q "$template8" $i/README.txt
           then
               echo "Found Tomcat 3.0.2 version with Tomcat8"
               encryptpassword  v302 $i
           else
               print "JVM was built with a different version of Tomcat and the password for key and keystore need to be encrypted mannually"
           fi
       fi
   fi
done
               
